Traceback (most recent call last):
  File "/home/pedro/PINN/jaxpi/examples/geomII/main.py", line 39, in <module>
    app.run(main)
  File "/usr/local/lib/python3.11/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.11/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/home/pedro/PINN/jaxpi/examples/geomII/main.py", line 31, in main
    train.train_and_evaluate(FLAGS.config, FLAGS.workdir)
  File "/home/pedro/PINN/jaxpi/examples/geomII/train.py", line 73, in train_and_evaluate
    u_ref = u_ref / U_star
            ^^^^^
UnboundLocalError: cannot access local variable 'u_ref' where it is not associated with a value