I0603 18:04:55.594810 129682137858048 train.py:290] Training time window 1
Traceback (most recent call last):
  File "/home/pedro/PINN/jaxpi/examples/geomI_2ph/main.py", line 39, in <module>
    app.run(main)
  File "/usr/local/lib/python3.11/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.11/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/home/pedro/PINN/jaxpi/examples/geomI_2ph/main.py", line 31, in main
    train.train_and_evaluate(FLAGS.config, FLAGS.workdir)
  File "/home/pedro/PINN/jaxpi/examples/geomI_2ph/train.py", line 369, in train_and_evaluate
    model = train_one_window(config, workdir, model, samplers, idx)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro/PINN/jaxpi/examples/geomI_2ph/train.py", line 129, in train_one_window
    model.state = model.step(model.state, batch)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/jaxpi/models.py", line 171, in step
    grads = grad(self.loss)(state.params, state.weights, batch, *args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/jaxpi/models.py", line 124, in loss
    losses = self.losses(params, batch, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro/PINN/jaxpi/examples/geomI_2ph/models.py", line 364, in losses
    params, self.inflow_coords[:, 0], self.inflow_coords[:, 1]
            ^^^^^^^^^^^^^^^^^^
AttributeError: 'NavierStokes2DwSat' object has no attribute 'inflow_coords'
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
Waiting for JIT...